### ISSUE TITLE
[question] AVG display on pop window

### ISSUE THREAD

**Issue by ShodiyorK** [nofear-js/faceit-vision-old-version#1]
can we hope for it? or is there any way to do it in python?

**Comment by nofear-js** [comment]
This is an old version, I am unlikely to update it. Such statistics are only available in the current version 1.5.6 (She is private)

**Comment by Lines08** [comment]
Sorry for commenting on a closed issue.

are you selling the private version in any way?

**Comment by nofear-js** [comment]
extension fix, not work anymore :( sorry

пт, 24 июл. 2020 г. в 16:23, Leon | Lines <notifications@github.com>:
