### ISSUE TITLE
Does your Private version still work?

### ISSUE THREAD

**Issue by supagithub** [nofear-js/faceit-vision-old-version#2]
let me know please i dont mind spending some money on it.

**Comment by ShodiyorK** [comment]
i don't think it does. i doubt they fixed their api

**Comment by nickyhellatrigger** [comment]
I would like to have the update too

**Comment by ShodiyorK** [comment]
extension will not work anymore. even if it will get updated

**Comment by nofear-js** [comment]
My private version was also fixed. Because the same way of getting data was used. It is unlikely that the expansion will appear again in the future.
